export const APIPartnerFields = {
    crit: [
        'accountID',
        'advertiserName',
        'currency',
        'campaignName',
        'campaignID',
        'dateTimePosix',
        'dateTime',
        'click',
        'impressions',
        'CTR',
        'revcpc',
        'ecpm',
        'cost',
        'sales',
        'convRate',
        'orderValue',
        'salesPostView',
        'convRatePostView',
        'orderValuePostView',
        'costOfSale',
        'overallCompetitionWin',
        'costPerOrder'
    ],
    rock: ['date',
        'campaign_name',
        'campaign_id',
        'campaign_currency',
        'campaign_time_zone',
        'advertiser_name',
        'advertiser_id',
        'placement',
        'ad_size',
        'line_item_name',
        'line_item_id',
        'publisher_name',
        'advertisement_id',
        'advertisement_name',
        'advertisement_type',
        'thirdparty_ad_id',
        'spend',
        'impressions',
        'clicks',
        'conversions',
        'video_starts',
        'video_first_quartile_reached',
        'video_midpoint_reached',
        'video_third_quartile_reached',
        'video_completions'
    ],
    goad: ['Day',
        'Account',
        'Customer ID',
        'Client name',
        'Campaign ID',
        'Campaign',
        'Currency',
        'Ad',
        'Ad ID',
        'Headline 1',
        'Headline 2',
        'Ad group ID',
        'Ad group',
        'Impressions',
        'Clicks',
        'Conversions',
        'Views',
        'Video played to 25%',
        'Video played to 50%',
        'Video played to 75%',
        'Video played to 100%',
        'Cost'
    ],
    gdbm: ['Date',
        'Advertiser',
        'Advertiser ID',
        'Advertiser Status',
        'Advertiser Integration Code',
        'Campaign',
        'Campaign ID',
        'Partner',
        'Partner ID',
        'Partner Status',
        'Creative',
        'Creative ID',
        'DCM Placement ID',
        'Creative Status',
        'Creative Source',
        'Creative Integration Code',
        'Creative Width',
        'Creative Height',
        'Advertiser Currency',
        'Impressions',
        'Clicks',
        'Total Conversions',
        'Starts (Video)',
        'First-Quartile Views (Video)',
        'Midpoint Views (Video)',
        'Third-Quartile Views (Video)',
        'Complete Views (Video)',
        'CPM Fee 1 (Adv Currency)',
        'Media Cost (Advertiser Currency)',
        'Data Fees (Adv Currency)',
        'Total Media Cost (Advertiser Currency)'
    ]
};
